version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - frontend


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      PORT: 5000
      ORIGIN: http://localhost:5000 
