services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      FRONTEND_URL: http://localhost:5050
    depends_on:
      - mongodb


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PUBLIC_CLIENT_SIDE_FORTUNA_API_BASE_URL: http://localhost:8000/api
        PUBLIC_SERVER_SIDE_FORTUNA_API_BASE_URL: http://backend:8000/api
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      PORT: 5050
      ORIGIN: http://localhost:5050


  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: